#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# Protect master and main from accidental commits.
branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'master' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed!\n" && exit 1
fi

if [ $branchName == 'main' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed!\n" && exit 1
fi

exit 0

npm run lint
npm run test
