name: Test Code
on:
  pull_request:
  push:
    branches:
      - develop/*
jobs:
  test-code:
    environment:
      name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install
      
      - name: Test Lint
        run: npm run lint
        
      - name: Test coverage
        run: npm run test
      
      - name: Set homepage
        run: npm run setHomepage


      - name: Build
        run: CI=false npm run build
      
      - name: Deploy Netlify
        run : netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN}} --site ${{ secrets.NETLIFY_SITE_ID}}
  PR:
    needs: test-code
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Get name
        id: get-branch 
        uses: ypicard/get-branch-name-github-action@v1    

      - name: create pull request
        run: gh pr create -B main -H ${{ steps.get-branch.outputs.branch }} --title 'Merge develop into main' --body 'Created PR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}